trigger:
- master

resources :
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName:  Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker1'
        repository: 'kausikisamadder/devopsfile'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifact@1
      inputs: 
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
 
  pool:
    vmImage: 'ubuntu-latest'
   steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      itemPattern: '**/*yaml'
      targetPath: '$(system.ArtifactDirectory)'
    - task: kubernetManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'kausikiservice'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/deploy2.yaml'
        containers:'kausikisamadder/devopsfile:$(tag)'
